### ISSUE TITLE
How to download daily/monthly ERA5 model level data?

### ISSUE THREAD

**Issue by pppp-777** [zxdawn/zxdawn.github.io#806]
Sorry to bother you.However, I have a question. 
Can I download daily or monthly model  level data? What should I do?
Thanks!

**Comment by zxdawn** [comment]
You can check the tutorial on my [website](https://dreambooker.site/2018/04/20/Initializing-the-WRF-model-with-ERA5/#/model-level-data-getera5-ml-py).

**Comment by pppp-777** [comment]
Thank! I saw it before, but I don't know why that I can't leave the message on that website. It helps me a lot. 
However, it mentioned that 
` 'date':'DATE1/to/DATE2',
 'time':'00:00:00/03:00:00/06:00:00/09:00:00/12:00:00/15:00:00/18:00:00/21:00:00',` .

I don't know how to set the time interval if I need daily model level data. Maybe I can downdload hourly data and average them, but it will take me a lot of time.

**Comment by zxdawn** [comment]
Because there're so many advertisements through the comment system, I closed it.

Anyway, I suppose these methods below are useful instead of downloading hourly data:
- [ERA5 Daily Aggregates](https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_DAILY)
- [Daily statistics](https://cds.climate.copernicus.eu/cdsapp#!/software/app-c3s-daily-era5-statistics?tab=app)
- [Related stackoverflow question](https://earthscience.stackexchange.com/q/18679)

Hope you can find the solution ;)

**Comment by pppp-777** [comment]
Thanks! I will read these carefully.
